spring.application.name=36_microservicio_formacion_acceso_oauth2
server.port=9005
server.servlet.context-path=/formacion

remote.url=http://localhost:8005/escuela/

remote.user=root
remote.password=root
oauth2.url=http://localhost:8080/realms/testrealm/protocol/openid-connect/token
oauth2.clientId=testclient
oauth2.grantType=password
