spring.application.name=37_microservicio_formacion_feignclient_clienteOAuth2
server.port=9005
server.servlet.context-path=/formacion

rremote.url=http://localhost:8005/escuela/

remote.user=root
remote.password=root
oauth2.url=http://localhost:8080/realms/testrealm/protocol/openid-connect/token
oauth2.clientId=testclient
oauth2.grantType=password
