apiVersion: apps/v1
kind: Deployment
metadata:
  name: alumnos-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alumnos
  template:
    metadata:
      labels:
        app: alumnos
    spec:
      containers:
        - name: alumnos-container
          image: imgalumnos  # Usa la imagen Docker local
          imagePullPolicy: Never
          ports:
            - containerPort: 8500  # Puerto dentro del contenedor
          env:
             - name: SPRING_PROFILES_ACTIVE
               value: "prod"
             - name: HOST_DB
               value: "10.2.1.60"
             - name: PORT_DB
               value: "3306"
             - name: USER_DB
               value: root
             - name: PASS_DB
               value: root